version: 2

models:
  - name: fact_page_views
    description: "Fact table for page view eventd by product level"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null